# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
#org.gradle.debug=false
mappingsVersion = 2023.08.13-1.20.1
modMixinVersion = 0.8.5
mappingsChannel = parchment
modGroup = fr.romain77.antiqueatlas

## Publishing Porperties
_curseforge_id = 1062668
_modrinth_id   = Y1t4glur
## Environment Properties
_minecraft_version     = 1.20.1
_minecraft_version_min = 1.20.1
_minecraft_version_max = 1.20.2
_loader                = Forge
_loader_file           = META-INF/mods.toml
_loader_version        = 47.4.0
_loader_version_min    = 47
_loader_version_max    = 48
## Mod Properties
_mod_name          = Antique Atlas TFOT
_mod_id            = antiqueatlas
_mod_version       = 8.2.0-tfot.4
_mod_release       = alpha
_mod_environment   = client
_mod_license       = GNU GENERAL PUBLIC LICENSE
_mod_authors       = Hunternif, tyra314, Stereowalker, 77Romain77
_mod_issue_tracker = https://github.com/77Romain77/AntiqueAtlas_TFOT/issues
_mod_page          = https://github.com/77Romain77/AntiqueAtlas_TFOT
_mod_description   = A fully client-side Forge 1.20.1 atlas with local maps per server, multiple named profiles and no permanent minimap.
##Misc Properties
